#!/usr/bin/env python3
"""Generate SSD1306 page-oriented 8x16 ASCII and 16x16 GB2312 glyphs."""

from __future__ import annotations

import argparse
import struct
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


GB2312_CHARACTER_COUNT = 7445
ASCII_FIRST = 0x20
ASCII_LAST = 0x7E
GLYPH_HEIGHT = 16
FONT_MAGIC = 0x32334247
FONT_VERSION = 1
FONT_ENTRY_SIZE = 34


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", type=Path, required=True)
    parser.add_argument("--output-ascii", type=Path, required=True)
    parser.add_argument("--output-bin", type=Path, required=True)
    parser.add_argument("--output-hex", type=Path, required=True)
    parser.add_argument("--flash-address", type=lambda value: int(value, 0), required=True)
    parser.add_argument("--font-size", type=int, default=14)
    parser.add_argument("--threshold", type=int, default=96)
    return parser.parse_args()


def collect_gb2312_characters() -> list[tuple[int, str]]:
    characters: dict[int, str] = {}

    for lead in range(0xA1, 0xF8):
        for trail in range(0xA1, 0xFF):
            try:
                character = bytes((lead, trail)).decode("gb2312")
            except UnicodeDecodeError:
                continue

            if len(character) == 1:
                characters[ord(character)] = character

    result = sorted(characters.items())
    if len(result) != GB2312_CHARACTER_COUNT:
        raise RuntimeError(
            f"Expected {GB2312_CHARACTER_COUNT} GB2312 characters, got {len(result)}"
        )
    return result


def render_glyph(
    character: str,
    target_width: int,
    font: ImageFont.FreeTypeFont,
    threshold: int,
) -> list[int]:
    probe = Image.new("L", (64, 64), 0)
    probe_draw = ImageDraw.Draw(probe)
    left, top, right, bottom = probe_draw.textbbox((0, 0), character, font=font)
    glyph_width = max(1, right - left)
    glyph_height = max(1, bottom - top)

    glyph = Image.new("L", (glyph_width, glyph_height), 0)
    ImageDraw.Draw(glyph).text((-left, -top), character, font=font, fill=255)

    scale = min(target_width / glyph_width, GLYPH_HEIGHT / glyph_height, 1.0)
    if scale < 1.0:
        resized_width = max(1, round(glyph_width * scale))
        resized_height = max(1, round(glyph_height * scale))
        glyph = glyph.resize((resized_width, resized_height), Image.Resampling.LANCZOS)

    canvas = Image.new("L", (target_width, GLYPH_HEIGHT), 0)
    offset_x = (target_width - glyph.width) // 2
    offset_y = (
        GLYPH_HEIGHT - glyph.height - 2
        if character == "."
        else (GLYPH_HEIGHT - glyph.height) // 2
    )
    canvas.paste(glyph, (offset_x, offset_y))

    packed: list[int] = []
    pixels = canvas.load()
    for page in range(2):
        for x in range(target_width):
            value = 0
            for bit in range(8):
                if pixels[x, page * 8 + bit] >= threshold:
                    value |= 1 << bit
            packed.append(value)
    return packed


def format_bytes(values: list[int]) -> str:
    return ",".join(f"0x{value:02X}U" for value in values)


def intel_hex_record(address: int, record_type: int, data: bytes) -> str:
    payload = bytes((len(data), (address >> 8) & 0xFF, address & 0xFF, record_type)) + data
    checksum = (-sum(payload)) & 0xFF
    return ":" + (payload + bytes((checksum,))).hex().upper()


def write_intel_hex(data: bytes, flash_address: int, output_path: Path) -> None:
    lines: list[str] = []
    current_upper = -1

    for offset in range(0, len(data), 16):
        absolute_address = flash_address + offset
        upper = absolute_address >> 16
        if upper != current_upper:
            lines.append(intel_hex_record(0, 0x04, upper.to_bytes(2, "big")))
            current_upper = upper
        lines.append(
            intel_hex_record(absolute_address & 0xFFFF, 0x00, data[offset : offset + 16])
        )
    lines.append(intel_hex_record(0, 0x01, b""))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="ascii", newline="\n")


def generate_font_files(
    font_path: Path,
    ascii_output_path: Path,
    binary_output_path: Path,
    hex_output_path: Path,
    flash_address: int,
    font_size: int,
    threshold: int,
) -> None:
    font = ImageFont.truetype(str(font_path), font_size)
    gb2312_characters = collect_gb2312_characters()

    ascii_lines = [
        "/* Generated by Hardware/Tools/My_generate_oled_gb2312.py. */",
        "/* Source font: Noto Sans SC, licensed under SIL Open Font License 1.1. */",
        "",
        "static const uint8_t My_oled_ascii_8x16_My[95][16] = {",
    ]
    for codepoint in range(ASCII_FIRST, ASCII_LAST + 1):
        glyph = render_glyph(chr(codepoint), 8, font, threshold)
        ascii_lines.append(f"  {{{format_bytes(glyph)}}},")
    ascii_lines.extend(["};", ""])
    ascii_output_path.parent.mkdir(parents=True, exist_ok=True)
    ascii_output_path.write_text(
        "\n".join(ascii_lines), encoding="ascii", newline="\n"
    )

    font_data = bytearray(
        struct.pack(
            "<IHHII",
            FONT_MAGIC,
            FONT_VERSION,
            len(gb2312_characters),
            FONT_ENTRY_SIZE,
            0,
        )
    )
    for codepoint, character in gb2312_characters:
        glyph = render_glyph(character, 16, font, threshold)
        font_data.extend(struct.pack("<H", codepoint))
        font_data.extend(glyph)

    binary_output_path.parent.mkdir(parents=True, exist_ok=True)
    binary_output_path.write_bytes(font_data)
    write_intel_hex(font_data, flash_address, hex_output_path)


def main() -> None:
    arguments = parse_arguments()
    generate_font_files(
        arguments.font,
        arguments.output_ascii,
        arguments.output_bin,
        arguments.output_hex,
        arguments.flash_address,
        arguments.font_size,
        arguments.threshold,
    )
    print(
        f"Generated {GB2312_CHARACTER_COUNT} GB2312 glyphs at "
        f"0x{arguments.flash_address:08X}"
    )


if __name__ == "__main__":
    main()
